# Generated by Django 5.2.6 on 2025-09-30 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='عنوان آیتم ToDo', max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='توضیحات بیشتر برای آیتم')),
                ('completed', models.BooleanField(default=False, help_text='آیا آیتم انجام شده است؟')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی')),
                ('user', models.ForeignKey(help_text='کاربری که این آیتم متعلق به اوست', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo Item',
                'verbose_name_plural': 'Todo Items',
                'ordering': ['-updated_at'],
            },
        ),
    ]
